# Spring Datasource - l\u00EA a URL completa do Render
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Swagger e H2
springdoc.swagger-ui.path=/swagger-ui.html
spring.h2.console.enabled=false